### ISSUE TITLE
deleteUser Function

### ISSUE THREAD

**Issue by qwerttttyy** [twelfd/PhpEmbyUserApi#1]
Hi, thanks for your fantastic work! you really helped me a lot.
I only have a problem in the deleteUser function, it does not delete the user and return the error  "Bad Request (Invalid Content-Length.)" 

Thank you! Best regards.

**Comment by qwerttttyy** [comment]
> Hi, thanks for your fantastic work! you really helped me a lot.
> I only have a problem in the deleteUser function, it does not delete the user and return the error "Bad Request (Invalid Content-Length.)"
> 
> Thank you! Best regards.

Ok, i solved =)

I think you forgot to send the id as postdata. In fact, I solved it by replacing:

`public function deleteUser($userid)
    {
        $url = "http://$this->embyIP:$this->embyPort/emby/Users/$userid?api_key=$this->embyApiKey";
        $customCurlRequest = "DELETE";
        return $this->curlExecute($url, null, $customCurlRequest);
    }`

with:

`    public function deleteUser($userid)
    {
        $url = "http://$this->embyIP:$this->embyPort/emby/Users/$userid?api_key=$this->embyApiKey";
		$postdata = array(
            "Id" => $userid,
        );
        $customCurlRequest = "DELETE";
        return $this->curlExecute($url, json_encode($postdata), $customCurlRequest);
    }`

Thanks for your fantastic work. I hope I have helped.

Best regards =)

**Comment by twelfd** [comment]
Thanks for the update - It's  while since I looked at this. If you open a pull request with the change I'll be happy/grateful to include  it.
